### ISSUE TITLE
Metadata input file

### ISSUE THREAD

**Issue by xuanxu** [openjournals/inara#1]
When calling Inara with the `-m` option the package accepts a metadata file used to compile the paper. 
The goal of this issue is to define the format of the expected metadata file.

:wave: @tarleb:

Proposal 1: 
A YAML file with this structure/fields:
```yaml
---
title: 'Nimbus: a Ruby gem to implement Random Forest algorithms in a genomic selection
  context'
tags:
- random forest
- genomics
- machine learning
- ruby
- open science
languages:
- Ruby
- TeX
authors:
- :given_name: Juanjo
  :middle_name:
  :last_name: Bazán
  :orcid: 0000-0001-7699-3983
  :affiliation: "Astroparticle Physics. CIEMAT, Madrid, Spain"
- :given_name: Oscar
  :middle_name:
  :last_name: Gonzalez-Recio
  :orcid: 0000-0002-9106-4063
  :affiliation: Genetics Department. INIA, Madrid, Spain
doi: 10.21105/joss.00351
software_repository_url: https://github.com/xuanxu/nimbus
reviewers:
- "@gemgon"
- "@pjotrp"
volume: 6
issue: 67
year: 2021
page: 15
journal_alias: joss
software_review_url: https://github.com/openjournals/joss-reviews/issues/351
archive_doi: ''
citation_string: 'Bazán et al., (2021). Nimbus: a Ruby gem to implement Random Forest
  algorithms in a genomic selection context. Journal of Open Source Software, 6(67),
  15, https://doi.org/10.21105/joss.00351'
editor:
  :github_user: "@xuanxu"
  :name: Juanjo Bazán
  :url: https://juanjobazan.com
  :orcid: 0000-0001-7699-3983
submitted_at: "12 July 2017"
published_at: "18 August 2017"
```

PROPOSAL 2: The same info but as JSON, no preference on my part.

Ideally any field could be empty or null, so for example when compiling a draft for a not-yet-published/under-review paper fields like `editor`, `reviewers`, `archive_doi`, `published_at`, etc would be empty. (I could fill them in with placeholder text/values if needed).
