### ISSUE TITLE
Editor metadata ignored

### ISSUE THREAD

**Issue by xuanxu** [openjournals/inara#3]
It seems like currently the editor metadata is ignored when included in the metadata file.
The passed values are
```yaml
editor:
  github_user: "xuanxu"
  name: Juanjo Bazán
  url: https://juanjobazan.com
  orcid: 0000-0001-7699-3983
```
sometimes all of the values will be null or empty (when compiling a draft before the review has an editor assigned), sometimes some of them will be null or empty (when editor has not provide url or orcid)
