### ISSUE TITLE
getopt: unrecognized option: c

### ISSUE THREAD

**Issue by platipodium** [openjournals/inara#34]
Inara Docker image in CI pipeline fails with `getopt: unrecognized option: c`

```
Running with gitlab-runner 15.10.0-hifis0 (285ec021)
  on hifis-runner-manager-1 qSeqXZze, system ID: s_18a5a67640b5

Preparing the "docker+machine" executor
00:20
Using Docker executor with image openjournals/inara:latest ...
Pulling docker image openjournals/inara:latest ...
Using docker image sha256:a880d6aaa55fe9e8d7d0ffd102d531595ef3e5d8f219e0cb9dcb7bbc2bf3b317 for openjournals/inara:latest with digest openjournals/inara@sha256:86d957f2226bc8010e386180206144c2362fad02b3331ebe300cc1d6088131d9 ...

Preparing environment
00:01
Running on runner-qseqxzze-project-4399-concurrent-0 via runner-qseqxzze-hifis-autoscale-1680471447-19e9c35a...

Getting source from Git repository
00:01
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/mussel/netlogo-northsea-species/.git/
Created fresh repository.
Checking out e085305e as detached HEAD (ref is main)...
Skipping Git submodules setup

Executing "step_script" stage of the job script
00:00
Using docker image sha256:a880d6aaa55fe9e8d7d0ffd102d531595ef3e5d8f219e0cb9dcb7bbc2bf3b317 for openjournals/inara:latest with digest openjournals/inara@sha256:86d957f2226bc8010e386180206144c2362fad02b3331ebe300cc1d6088131d9 ...
getopt: unrecognized option: c

Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by tarleb** [comment]
Thanks for the report. I've updated the entryscript, so it will now reply with a more helpful message.

```
getopt: unrecognized option: c
Usage: /usr/local/bin/inara [OPTIONS] INPUT_FILE
Options:
        -l: create log files for all formats
        -m: article info file; YAML file contains article metadata
        -o: comma-separated list of output format; defaults to jats,pdf
        -p: flag to force the production of a publishing PDF
        -v: increase verbosity; can be given multiple times
```

**Comment by platipodium** [comment]
Curiously, I don't see how I would have set the option `-c`.  Here the `.gitlab-ci.yml` section used to trigger the build (and fail)

```
joss-paper:
  stage: deploy
  image: 'openjournals/inara:latest'
  script:
    - inara -o pdf,cff doc/joss/paper.md
  variables:
    GIT_SHA: $CI_COMMIT_SHA
    JOURNAL: joss
```

So why do I get the `unrecognised option -c` error on the CI pipeline?

**Comment by zyzzyxdonta** [comment]
I have the same problem. This is because the Docker image is not able to handle what is happening in GitLab CI. Before the user-provided `before_script` and `script` are run, GitLab CI tries to clone your repo into the container. The first option it passes to git is `-c`. You can reproduce this by running

```bash
docker run --rm openjournals/inara git -c
```

which gives the same result.

You can prevent this behaviour by setting the variable `GIT_STRATEGY: none` in your `.gitlab-ci.yml`. But then you will be missing the code for your paper as the repository is not cloned.

I would suggest reopening this issue and maybe change the title to reflect the actual problem: The container doesn't work with GitLab CI because you can not pass scripts to it; just arguments to the hard-coded program.

I think it would be quite valuable to have it working as GitLab is quite a common tool these days and is used in many research institutions, including the [Helmholtz Association](https://en.wikipedia.org/wiki/Helmholtz_Association) (for which both @platipodium and I, and thousands of other scientists work).

Thank you in advance!

**Comment by platipodium** [comment]
Thanks for the hints above, I also got it to work with `entrypoint`, does not seem to need git.  Here's the production version from my `.gitlab-ci.yml` FYR:

```
joss-inara:
  stage: deploy
  image:
    name: openjournals/inara
    entrypoint: ["/bin/sh", "-c"]
  variables:
    GIT_SHA: $CI_COMMIT_SHA
    JOURNAL: joss
  script:
    - echo "Calling inara -o pdf,cff doc/joss/paper.md" 
    - inara -o pdf,cff doc/joss/paper.md
  artifacts:
    paths:
      - ./doc/joss/paper.pdf
      - ./doc/joss/CITATION.cff
  needs: []
```
