### ISSUE TITLE
Can the latex template print the corresponding author's email in the paper's header?

### ISSUE THREAD

**Issue by abpoll** [openjournals/inara#55]
In the example paper.md, the corresponding author adds their email: https://github.com/openjournals/inara/blob/main/example/paper.md?plain=1. As far as I can tell, the GitHub action does not print the corresponding author's email anywhere. It doesn't seem like the latex template is accessing this field. Is it possible to add this to the GitHub action? Some preprint servers ask authors to have at least one email on the preprint. Thanks!

**Comment by tarleb** [comment]
Good idea, thanks! Done.

**Comment by tarleb** [comment]
The corresponding author needs to have both the email and the `corresponding: true` field.

``` yaml
authors:
  - name: John Doe
    affiliation: [1, 2]
    orcid: 0000-0001-2345-5678
    email: j.doe@example.edu
    corresponding: true
```

If you have time, a PR to add this to the docs would be greatly appreciated.

**Comment by abpoll** [comment]
Re: adding to docs - Happy to. I will try to get to it soon. 

Re: markdown header - I have something that looks like that:

```
authors:
  - name: Adam Pollack
    corresponding: true
    email: adam.b.pollack@dartmouth.edu
    orcid: 0000-0001-6642-0591
    affiliation: 1
```

and I have the following github action

```
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: joss_submission/paper.md
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: joss_submission/paper.pdf
```

but I don't see the email show up in the pdf header (see below).

Sorry if I'm missing something super obvious. 

<img width="705" alt="Screenshot 2024-05-23 at 8 32 01 AM" src="https://github.com/openjournals/inara/assets/7188728/52cf56f4-23d3-4f1a-868c-df68d8157938">
