### ISSUE TITLE
Corresponding author email does not show up in joss pdf draft

### ISSUE THREAD

**Issue by abpoll** [openjournals/inara#57]
Hello, 

Referencing https://github.com/openjournals/inara/issues/55#issuecomment-2127014922.

Following https://github.com/openjournals/inara/commit/02c6106258965d82a0276b2136afda1f26bd8798, I added an email to a paper.md header for the corresponding author as follows:

```
authors:
  - name: Adam Pollack
    corresponding: true
    email: adam.b.pollack@dartmouth.edu
    orcid: 0000-0001-6642-0591
    affiliation: 1
```

I have the following GitHub action:

```
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: joss_submission/paper.md
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: joss_submission/paper.pdf
```

but I don't see the email show up in the pdf header (see below). Following https://github.com/openjournals/inara/commit/02c6106258965d82a0276b2136afda1f26bd8798, I expected to see the corresponding author email after the "Corresponding author" text. 

![image](https://github.com/openjournals/inara/assets/7188728/56376924-ae5e-4280-9de0-c1c0aadd790f)
